#!/bin/sh

export GUILE_LOAD_PATH="$PWD${GUILE_LOAD_PATH:+:}$GUILE_LOAD_PATH"
export GUIX_PACKAGE_PATH="$PWD/.guix-package-path${GUIX_PACKAGE_PATH:+:}$GUIX_PACKAGE_PATH"

# If this is being run as a script
if [ "${BASH_SOURCE[0]}" = "${0}" ]; then
    # To avoid $XDG_CONFIG_HOME/guix/latest from being used
    export XDG_CONFIG_HOME="${GDS_GUIX_CUSTOM_XDG_CONFIG_HOME:-"/dev/null"}"

    $@
fi
