(define-module (gds systems govuk production)
  #:use-module (srfi srfi-1)
  #:use-module (srfi srfi-26)
  #:use-module (ice-9 match)
  #:use-module (ice-9 rdelim)
  #:use-module (ice-9 regex)
  #:use-module (gnu)
  #:use-module (gnu services admin)
  #:use-module (gnu services databases)
  #:use-module (gnu services networking)
  #:use-module (gnu services ssh)
  #:use-module (gnu services web)
  #:use-module (guix build utils)
  #:use-module (guix download)
  #:use-module (guix gexp)
  #:use-module (guix packages)
  #:use-module (guix store)
  #:use-module (gds packages govuk)
  #:use-module (gds packages guix)
  #:use-module (gds packages utils custom-sources)
  #:use-module (gds services)
  #:use-module (gds services base)
  #:use-module (gds services govuk)
  #:use-module (gds services govuk content-access-limits)
  #:use-module (gds services govuk nginx)
  #:use-module (gds services govuk plek)
  #:use-module (gds services govuk router)
  #:use-module (gds services govuk routing-configuration)
  #:use-module (gds services govuk signon)
  #:use-module (gds services govuk tailon)
  #:use-module (gds services rails)
  #:use-module (gds services utils databases elasticsearch)
  #:use-module (gds services utils databases mongodb)
  #:use-module (gds services utils databases mysql)
  #:use-module (gds services utils databases postgresql)
  #:use-module (gds services utils databases)
  #:use-module (gds services utils)
  #:use-module (gds systems govuk base)
  #:export (govuk-production-os))

(define govuk-production-os
  (operating-system
    (host-name "govuk-production")
    (timezone "Europe/London")
    (locale "en_GB.UTF-8")
    (bootloader (bootloader-configuration
                 (bootloader grub-bootloader)
                 (target "/dev/sdX")))
    ;; TODO: Including this causes an error for some reason...
    ;; ERROR: Unbound variable: useful-packages
    ;(packages useful-packages)
    (skeletons (remove (match-lambda
                         ((file source)
                          (member file '(".bashrc"))))
                       (default-skeletons)))
    (file-systems
     (cons (file-system
             (device "my-root")
             (title 'label)
             (mount-point "/")
             (type "ext4"))
           %base-file-systems))
    (services (setup-services
               (append base-services optional-services)))))
